name: "Continuous Integration (CLang)"

on: [push, pull_request]

jobs:
  clang:
    name: Clang
    needs: clang-format
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - clang: '3.5'
          - clang: '3.6'
          - clang: '3.7'
          - clang: '3.8'
          - clang: '3.9'
          - clang: '4.0'
          - clang: '5.0'
          - clang: '6.0'
          - clang: '7'
          - clang: '8'
            cxxflags: -fsanitize=leak
          - clang: '9'
            cxxflags: -fsanitize=undefined
          - clang: '10'
            cxxflags: -fsanitize=address
    steps:
      - name: Install
        run: |
          sudo add-apt-repository -yn 'deb http://archive.ubuntu.com/ubuntu/ trusty main'
          sudo add-apt-repository -yn 'deb http://archive.ubuntu.com/ubuntu/ trusty universe'
          sudo add-apt-repository -yn 'deb http://archive.ubuntu.com/ubuntu/ xenial main'
          sudo add-apt-repository -yn 'deb http://archive.ubuntu.com/ubuntu/ xenial universe'
          sudo add-apt-repository -yn 'deb http://archive.ubuntu.com/ubuntu/ bionic main'
          sudo add-apt-repository -yn 'deb http://archive.ubuntu.com/ubuntu/ bionic universe'
          sudo apt-get update
          sudo apt-get install -y clang-${{ matrix.clang }}
        if: ${{ matrix.clang < 8 }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Debug .
        env:
          CC: clang-${{ matrix.clang }}
          CXX: clang++-${{ matrix.clang }}
          CXXFLAGS: ${{ matrix.cxxflags }}
      - name: Build
        run: cmake --build .
      - name: Test
        run: ctest --output-on-failure -C Debug .